# Use the official Node.js runtime as a base image
FROM node:18

# Set the working directory in the container to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install the application dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Transpile TypeScript to JavaScript
RUN npm run build

# Expose the application on port 5127
EXPOSE 5127

# Define the command to run the application
CMD ["node", "dist/index.js"]
