### Recipe API

### Localhost Query Examples

### Get a single recipe
POST http://localhost:5127/graphql
Content-Type: application/json

{
  "query": "{ recipe(id: \"6529e0aed3fb818c8bc06ad9\") { name ingredients steps prepTime cookTime cuisineType calories imageUrl } }"
}

### Get all recipes
POST http://localhost:5127/graphql
Content-Type: application/json

{
  "query": "{ recipes { name ingredients steps prepTime cookTime cuisineType calories imageUrl } }"
}

### Add a new recipe
POST http://localhost:5127/graphql
Content-Type: application/json

{
  "query": "mutation { addRecipe(name: \"Test8\", ingredients: [\"Flour\", \"Milk\", \"Eggs\"], steps: [\"Mix ingredients\", \"Cook on pan\"], prepTime: 10, cookTime: 5, cuisineType: \"American\", calories: 200, imageUrl: \"https://example.com/pancakes.jpg\") { name } }"
}

### Update a recipe
POST http://localhost:5127/graphql
Content-Type: application/json

{
  "query": "mutation { updateRecipe(id: \"6529e0aed3fb818c8bc06ad9\", name: \"Pancakes\", ingredients: [\"Flour\", \"Water\", \"Eggs\"], steps: [\"Mix ingredients\", \"Cook on pan\"], prepTime: 10, cookTime: 5, cuisineType: \"American\", calories: 200, imageUrl: \"https://example.com/pancakes.jpg\") { name } }"
}

### Delete a recipe
POST http://localhost:5127/graphql
Content-Type: application/json

{
  "query": "mutation { deleteRecipe(id: \"652a1ec6307856a4dbe9f414\") { name } }"
}

### Production Query Examples

### Get a single recipe
POST https://cse-341-ms-project.onrender.com/graphql
Content-Type: application/json

{
  "query": "{ recipe(id: \"6529e0aed3fb818c8bc06ad9\") { name ingredients steps prepTime cookTime cuisineType calories imageUrl } }"
}

### Get all recipes
POST https://cse-341-ms-project.onrender.com/graphql
Content-Type: application/json

{
  "query": "{ recipes { name ingredients steps prepTime cookTime cuisineType calories imageUrl } }"
}

