### Recipe API Test Examples for Recipes

### Localhost Query Examples

### Get a single recipe
POST http://localhost:5127/graphql
Content-Type: application/json
Authorization: Bearer eJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdfV1o3dkU3Q3lLVDQyTGJ0TWNuLSJ9.eyJpc3MiOiJodHRwczovL2Rldi1oZGljM2o4cnhxc3EzZXZrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJUdDJSQ1FiTlpQdmluaTJDYlloc0haM3pJSm1vakViUEBjbGllbnRzIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MTI3L2dyYXBocWwiLCJpYXQiOjE2OTkxNDQ0MzksImV4cCI6MTY5OTIzMDgzOSwiYXpwIjoiVHQyUkNRYk5aUHZpbmkyQ2JZaHNIWjN6SUptb2pFYlAiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.CsSTHtFNiKvvozoSfA4OxylUX4WBxifWwGmnAXioZA9nXdvr5Pi1axzGYdxqmmdyDVUwmR0oziKxO7wFAtx7Ry1qQvXT-ryRce7cTNl3W9G8SO3Ud0LhparrvaEihKgkKwYnTlkWGCS97N_40nb1rdoyFZLuHXDfSmcArlJuFaOI_VwSakNzmXbO1GNkBZEZSrcnnJt8bpIYlkdEYf4Xfp98sPKZ7W1D8EHXPZELURr4VlCTswIX69g2mv9LuONvuKhb_LesVMpdRCOHPtXU5-Gg3fAXZBW7Q8w8pncpg09pAYNGSWsIVw8E55OSHFaR_EJmw1rgQm6ngJZDqQxY1g

{
  "query": "{ recipe(id: \"6529e0aed3fb818c8bc06ad9\") { id name ingredients steps prepTime cookTime cuisineType calories imageUrl } }"
}

### Get all recipes
POST http://localhost:5127/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdfV1o3dkU3Q3lLVDQyTGJ0TWNuLSJ9.eyJpc3MiOiJodHRwczovL2Rldi1oZGljM2o4cnhxc3EzZXZrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJUdDJSQ1FiTlpQdmluaTJDYlloc0haM3pJSm1vakViUEBjbGllbnRzIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MTI3L2dyYXBocWwiLCJpYXQiOjE2OTkxNDQ0MzksImV4cCI6MTY5OTIzMDgzOSwiYXpwIjoiVHQyUkNRYk5aUHZpbmkyQ2JZaHNIWjN6SUptb2pFYlAiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.CsSTHtFNiKvvozoSfA4OxylUX4WBxifWwGmnAXioZA9nXdvr5Pi1axzGYdxqmmdyDVUwmR0oziKxO7wFAtx7Ry1qQvXT-ryRce7cTNl3W9G8SO3Ud0LhparrvaEihKgkKwYnTlkWGCS97N_40nb1rdoyFZLuHXDfSmcArlJuFaOI_VwSakNzmXbO1GNkBZEZSrcnnJt8bpIYlkdEYf4Xfp98sPKZ7W1D8EHXPZELURr4VlCTswIX69g2mv9LuONvuKhb_LesVMpdRCOHPtXU5-Gg3fAXZBW7Q8w8pncpg09pAYNGSWsIVw8E55OSHFaR_EJmw1rgQm6ngJZDqQxY1g

{
  "query": "{ recipes { id name ingredients steps prepTime cookTime cuisineType calories imageUrl } }"
}

### Add a new recipe
POST http://localhost:5127/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdfV1o3dkU3Q3lLVDQyTGJ0TWNuLSJ9.eyJpc3MiOiJodHRwczovL2Rldi1oZGljM2o4cnhxc3EzZXZrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJUdDJSQ1FiTlpQdmluaTJDYlloc0haM3pJSm1vakViUEBjbGllbnRzIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MTI3L2dyYXBocWwiLCJpYXQiOjE2OTkxNDQ0MzksImV4cCI6MTY5OTIzMDgzOSwiYXpwIjoiVHQyUkNRYk5aUHZpbmkyQ2JZaHNIWjN6SUptb2pFYlAiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.CsSTHtFNiKvvozoSfA4OxylUX4WBxifWwGmnAXioZA9nXdvr5Pi1axzGYdxqmmdyDVUwmR0oziKxO7wFAtx7Ry1qQvXT-ryRce7cTNl3W9G8SO3Ud0LhparrvaEihKgkKwYnTlkWGCS97N_40nb1rdoyFZLuHXDfSmcArlJuFaOI_VwSakNzmXbO1GNkBZEZSrcnnJt8bpIYlkdEYf4Xfp98sPKZ7W1D8EHXPZELURr4VlCTswIX69g2mv9LuONvuKhb_LesVMpdRCOHPtXU5-Gg3fAXZBW7Q8w8pncpg09pAYNGSWsIVw8E55OSHFaR_EJmw1rgQm6ngJZDqQxY1g

{
  "query": "mutation { addRecipe(name: \"Test14\", ingredients: [\"Flour\", \"Milk\", \"Eggs\"], steps: [\"Mix ingredients\", \"Cook on pan\"], prepTime: 10, cookTime: 5, cuisineType: \"American\", calories: 200, imageUrl: \"https://example.com/pancakes.jpg\") { id name } }"
}

### Update a recipe
POST http://localhost:5127/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdfV1o3dkU3Q3lLVDQyTGJ0TWNuLSJ9.eyJpc3MiOiJodHRwczovL2Rldi1oZGljM2o4cnhxc3EzZXZrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJUdDJSQ1FiTlpQdmluaTJDYlloc0haM3pJSm1vakViUEBjbGllbnRzIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MTI3L2dyYXBocWwiLCJpYXQiOjE2OTkxNDQ0MzksImV4cCI6MTY5OTIzMDgzOSwiYXpwIjoiVHQyUkNRYk5aUHZpbmkyQ2JZaHNIWjN6SUptb2pFYlAiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.CsSTHtFNiKvvozoSfA4OxylUX4WBxifWwGmnAXioZA9nXdvr5Pi1axzGYdxqmmdyDVUwmR0oziKxO7wFAtx7Ry1qQvXT-ryRce7cTNl3W9G8SO3Ud0LhparrvaEihKgkKwYnTlkWGCS97N_40nb1rdoyFZLuHXDfSmcArlJuFaOI_VwSakNzmXbO1GNkBZEZSrcnnJt8bpIYlkdEYf4Xfp98sPKZ7W1D8EHXPZELURr4VlCTswIX69g2mv9LuONvuKhb_LesVMpdRCOHPtXU5-Gg3fAXZBW7Q8w8pncpg09pAYNGSWsIVw8E55OSHFaR_EJmw1rgQm6ngJZDqQxY1g

{
  "query": "mutation { updateRecipe(id: \"653463b522a5d3aa1d9f3205\", input: {name: \"Ice Cream Sausage4\", ingredients: [\"Mud2\", \"Water\", \"meat\"], steps: [\"Mix ingredients\", \"Cook on pan\"], prepTime: 10, cookTime: 5, cuisineType: \"American\", calories: 200, imageUrl: \"https://example.com/pancakes.jpg\"}) { id name } }"
}

### Delete a recipe
POST http://localhost:5127/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdfV1o3dkU3Q3lLVDQyTGJ0TWNuLSJ9.eyJpc3MiOiJodHRwczovL2Rldi1oZGljM2o4cnhxc3EzZXZrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJUdDJSQ1FiTlpQdmluaTJDYlloc0haM3pJSm1vakViUEBjbGllbnRzIiwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MTI3L2dyYXBocWwiLCJpYXQiOjE2OTkxNDQ0MzksImV4cCI6MTY5OTIzMDgzOSwiYXpwIjoiVHQyUkNRYk5aUHZpbmkyQ2JZaHNIWjN6SUptb2pFYlAiLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.CsSTHtFNiKvvozoSfA4OxylUX4WBxifWwGmnAXioZA9nXdvr5Pi1axzGYdxqmmdyDVUwmR0oziKxO7wFAtx7Ry1qQvXT-ryRce7cTNl3W9G8SO3Ud0LhparrvaEihKgkKwYnTlkWGCS97N_40nb1rdoyFZLuHXDfSmcArlJuFaOI_VwSakNzmXbO1GNkBZEZSrcnnJt8bpIYlkdEYf4Xfp98sPKZ7W1D8EHXPZELURr4VlCTswIX69g2mv9LuONvuKhb_LesVMpdRCOHPtXU5-Gg3fAXZBW7Q8w8pncpg09pAYNGSWsIVw8E55OSHFaR_EJmw1rgQm6ngJZDqQxY1g

{
  "query": "mutation { deleteRecipe(id: \"6546e3620a39d2df1bc1722e\") { id name } }"
}

### Production Query Examples

### Get a single recipe
POST https://cse-341-ms-project.onrender.com/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdfV1o3dkU3Q3lLVDQyTGJ0TWNuLSJ9.eyJpc3MiOiJodHRwczovL2Rldi1oZGljM2o4cnhxc3EzZXZrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJKbkN4WkNoNHJ3RGdMb0YwSkZPMWUwWnNDcUlJajEzS0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9jc2UtMzQxLW1zLXByb2plY3Qub25yZW5kZXIuY29tL2dyYXBocWwiLCJpYXQiOjE2OTkxNDMwODgsImV4cCI6MTY5OTIyOTQ4OCwiYXpwIjoiSm5DeFpDaDRyd0RnTG9GMEpGTzFlMFpzQ3FJSWoxM0siLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.hBrbhD2YIm4mgHUo9qzGDkPECZq1bLu_QOvC5f0tTcmxISXTNYnmGBjEoyVL331SX3epVI10fbbOCGPVMKZifSvW6Rh2Kvyg44OttLJKwylL0AdGfLgrmUlq3b4HXMsG0-mCOLvkrSmUjnAW1o8oYDcGRUU0Gc8BckQ6XM2Sl9k9ib-AkzFK2VbllE1atsJCIwKdt5BKKFo1lt6VLXA-K7M6HuS4zdbroO1jRjheji4ElIRZLv_oaqymvKhx1z3i9po2zeqGkVEemTjHJEineoDOuKn7NOTt6oQnQrHnrZ9NhzTeUrJeCoplClgmAWVeea_xgcZbOyQzDpcEdRvqfg

{
  "query": "{ recipe(id: \"6529e0aed3fb818c8bc06ad9\") { id name ingredients steps prepTime cookTime cuisineType calories imageUrl } }"
}

### Get all recipes
POST https://cse-341-ms-project.onrender.com/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdfV1o3dkU3Q3lLVDQyTGJ0TWNuLSJ9.eyJpc3MiOiJodHRwczovL2Rldi1oZGljM2o4cnhxc3EzZXZrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJKbkN4WkNoNHJ3RGdMb0YwSkZPMWUwWnNDcUlJajEzS0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9jc2UtMzQxLW1zLXByb2plY3Qub25yZW5kZXIuY29tL2dyYXBocWwiLCJpYXQiOjE2OTkxNDMwODgsImV4cCI6MTY5OTIyOTQ4OCwiYXpwIjoiSm5DeFpDaDRyd0RnTG9GMEpGTzFlMFpzQ3FJSWoxM0siLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.hBrbhD2YIm4mgHUo9qzGDkPECZq1bLu_QOvC5f0tTcmxISXTNYnmGBjEoyVL331SX3epVI10fbbOCGPVMKZifSvW6Rh2Kvyg44OttLJKwylL0AdGfLgrmUlq3b4HXMsG0-mCOLvkrSmUjnAW1o8oYDcGRUU0Gc8BckQ6XM2Sl9k9ib-AkzFK2VbllE1atsJCIwKdt5BKKFo1lt6VLXA-K7M6HuS4zdbroO1jRjheji4ElIRZLv_oaqymvKhx1z3i9po2zeqGkVEemTjHJEineoDOuKn7NOTt6oQnQrHnrZ9NhzTeUrJeCoplClgmAWVeea_xgcZbOyQzDpcEdRvqfg

{
  "query": "{ recipes { id name ingredients steps prepTime cookTime cuisineType calories imageUrl } }"
}

### Add a new recipe
POST https://cse-341-ms-project.onrender.com/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdfV1o3dkU3Q3lLVDQyTGJ0TWNuLSJ9.eyJpc3MiOiJodHRwczovL2Rldi1oZGljM2o4cnhxc3EzZXZrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJKbkN4WkNoNHJ3RGdMb0YwSkZPMWUwWnNDcUlJajEzS0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9jc2UtMzQxLW1zLXByb2plY3Qub25yZW5kZXIuY29tL2dyYXBocWwiLCJpYXQiOjE2OTkxNDMwODgsImV4cCI6MTY5OTIyOTQ4OCwiYXpwIjoiSm5DeFpDaDRyd0RnTG9GMEpGTzFlMFpzQ3FJSWoxM0siLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.hBrbhD2YIm4mgHUo9qzGDkPECZq1bLu_QOvC5f0tTcmxISXTNYnmGBjEoyVL331SX3epVI10fbbOCGPVMKZifSvW6Rh2Kvyg44OttLJKwylL0AdGfLgrmUlq3b4HXMsG0-mCOLvkrSmUjnAW1o8oYDcGRUU0Gc8BckQ6XM2Sl9k9ib-AkzFK2VbllE1atsJCIwKdt5BKKFo1lt6VLXA-K7M6HuS4zdbroO1jRjheji4ElIRZLv_oaqymvKhx1z3i9po2zeqGkVEemTjHJEineoDOuKn7NOTt6oQnQrHnrZ9NhzTeUrJeCoplClgmAWVeea_xgcZbOyQzDpcEdRvqfg

{
  "query": "mutation { addRecipe(name: \"Test15\", ingredients: [\"Flour\", \"Milk\", \"Eggs\"], steps: [\"Mix ingredients\", \"Cook on pan\"], prepTime: 10, cookTime: 5, cuisineType: \"American\", calories: 200, imageUrl: \"https://example.com/pancakes.jpg\") { id name } }"
}

### Update a recipe
POST https://cse-341-ms-project.onrender.com/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdfV1o3dkU3Q3lLVDQyTGJ0TWNuLSJ9.eyJpc3MiOiJodHRwczovL2Rldi1oZGljM2o4cnhxc3EzZXZrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJKbkN4WkNoNHJ3RGdMb0YwSkZPMWUwWnNDcUlJajEzS0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9jc2UtMzQxLW1zLXByb2plY3Qub25yZW5kZXIuY29tL2dyYXBocWwiLCJpYXQiOjE2OTkxNDMwODgsImV4cCI6MTY5OTIyOTQ4OCwiYXpwIjoiSm5DeFpDaDRyd0RnTG9GMEpGTzFlMFpzQ3FJSWoxM0siLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.hBrbhD2YIm4mgHUo9qzGDkPECZq1bLu_QOvC5f0tTcmxISXTNYnmGBjEoyVL331SX3epVI10fbbOCGPVMKZifSvW6Rh2Kvyg44OttLJKwylL0AdGfLgrmUlq3b4HXMsG0-mCOLvkrSmUjnAW1o8oYDcGRUU0Gc8BckQ6XM2Sl9k9ib-AkzFK2VbllE1atsJCIwKdt5BKKFo1lt6VLXA-K7M6HuS4zdbroO1jRjheji4ElIRZLv_oaqymvKhx1z3i9po2zeqGkVEemTjHJEineoDOuKn7NOTt6oQnQrHnrZ9NhzTeUrJeCoplClgmAWVeea_xgcZbOyQzDpcEdRvqfg

{
  "query": "mutation { updateRecipe(id: \"653463b522a5d3aa1d9f3205\", input: {name: \"Pancakes 4\", ingredients: [\"Mud\", \"Water\", \"meat\"], steps: [\"Mix ingredients\", \"Cook on pan\"], prepTime: 10, cookTime: 5, cuisineType: \"American\", calories: 200, imageUrl: \"https://example.com/pancakes.jpg\"}) { id name } }"
}

### Delete a recipe
POST https://cse-341-ms-project.onrender.com/graphql
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjdfV1o3dkU3Q3lLVDQyTGJ0TWNuLSJ9.eyJpc3MiOiJodHRwczovL2Rldi1oZGljM2o4cnhxc3EzZXZrLnVzLmF1dGgwLmNvbS8iLCJzdWIiOiJKbkN4WkNoNHJ3RGdMb0YwSkZPMWUwWnNDcUlJajEzS0BjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9jc2UtMzQxLW1zLXByb2plY3Qub25yZW5kZXIuY29tL2dyYXBocWwiLCJpYXQiOjE2OTkxNDMwODgsImV4cCI6MTY5OTIyOTQ4OCwiYXpwIjoiSm5DeFpDaDRyd0RnTG9GMEpGTzFlMFpzQ3FJSWoxM0siLCJndHkiOiJjbGllbnQtY3JlZGVudGlhbHMifQ.hBrbhD2YIm4mgHUo9qzGDkPECZq1bLu_QOvC5f0tTcmxISXTNYnmGBjEoyVL331SX3epVI10fbbOCGPVMKZifSvW6Rh2Kvyg44OttLJKwylL0AdGfLgrmUlq3b4HXMsG0-mCOLvkrSmUjnAW1o8oYDcGRUU0Gc8BckQ6XM2Sl9k9ib-AkzFK2VbllE1atsJCIwKdt5BKKFo1lt6VLXA-K7M6HuS4zdbroO1jRjheji4ElIRZLv_oaqymvKhx1z3i9po2zeqGkVEemTjHJEineoDOuKn7NOTt6oQnQrHnrZ9NhzTeUrJeCoplClgmAWVeea_xgcZbOyQzDpcEdRvqfg

{
  "query": "mutation { deleteRecipe(id: \"6546e384a8f2771089e7c7ff\") { id name } }"
}

